//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;using Newtonsoft.Json; 

public partial class ExpPersonalCategory
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ExpPersonalCategory()
    {
        this.ExpenseRecords = new HashSet<ExpenseRecord>();
    }

    public int id { get; set; }
    public string Name { get; set; }
    public Nullable<System.Guid> OwnerId { get; set; }
    public Nullable<int> SortOrder { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]  
public virtual ICollection<ExpenseRecord> ExpenseRecords { get; set; }
    [JsonIgnore]  
public virtual ExpUser ExpUser { get; set; }
}
